/*******************************************************************************

This file has been generated by SoftKernelGenerator and controls what
TintModes, BlendModes and PixelFormats are supported in software rendering as
well as what blit operations have custom/optimized implementations.

The more supported, the more code is generated, resulting in a larger binary.

Generating optimized blits for all possible combinations can result in tens of
thousands of optimized render loops, growing the size of WonderGUI by many
megabytes.

The default wg_softkernels.cpp provides a good balance between size and performance
for modern desktop applications, supporting everyting but only optimizing most
important blit operations.

********************************************************************************

SUPPORTED MODES AND FORMATS

Tint modes:            None
                       Flat
                       GradientX
                       GradientY
                       GradientXY
                       (unsupported: none)

Blend modes:           Replace
                       Blend
                       Add
                       Subtract
                       Multiply
                       Invert
                       Min
                       Max
                       Morph
                       (unsupported: none)

Source formats:        BGR_8_sRGB
                       BGR_8_linear
                       BGRX_8_sRGB
                       BGRX_8_linear
                       BGRA_8_sRGB
                       BGRA_8_linear
                       BGRA_4_linear
                       BGR_565_linear
                       CLUT_8_sRGB
                       CLUT_8_linear
                       RGB_565_bigendian
                       A_8
                       (unsupported: none)

Destination formats:   BGR_8_sRGB
                       BGR_8_linear
                       BGRX_8_sRGB
                       BGRX_8_linear
                       BGRA_8_sRGB
                       BGRA_8_linear
                       BGRA_4_linear
                       BGR_565_linear
                       RGB_565_bigendian
                       A_8
                       (unsupported: none)


CUSTOM BLIT KERNELS DEFINITION #1

Operations:         StraightBlit
                    StraightTile
                    TransformBlitNearest
                    TransformClipBlitNearest
                    TransformTileNearest
                    TransformBlitBilinear
                    TransformClipBlitBilinear
                    TransformTileBilinear
                    
Tint Modes:         None
                    
Blend Modes:        Replace
                    Blend
                    
Source Formats:     BGR_8_sRGB
                    BGR_8_linear
                    BGRX_8_sRGB
                    BGRX_8_linear
                    BGRA_8_sRGB
                    BGRA_8_linear
                    BGRA_4_linear
                    BGR_565_linear
                    CLUT_8_sRGB
                    CLUT_8_linear
                    RGB_565_bigendian
                    A_8
                    
Destination Formats:BGR_8_sRGB
                    BGR_8_linear
                    BGRX_8_sRGB
                    BGRX_8_linear
                    BGRA_8_sRGB
                    BGRA_8_linear
                    BGRA_4_linear
                    BGR_565_linear
                    CLUT_8_sRGB
                    CLUT_8_linear
                    RGB_565_bigendian
                    A_8
                    

*******************************************************************************/
#ifndef WG_SOFTKERNELS_DEFAULT_DOT_H
#define WG_SOFTKERNELS_DEFAULT_DOT_H
#pragma once

#include <wg_softgfxdevice.h>

namespace wg
{
	bool addDefaultSoftKernels( SoftGfxDevice * pDevice );
};

#endif //WG_SOFTKERNELS_RGB565BE_DOT_H

